// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBusiness_DB;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyBusiness_DB.Migrations
{
    [DbContext(typeof(BusinessContext))]
    [Migration("20250524182936_EntityOrderAndRelProduct")]
    partial class EntityOrderAndRelProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyBusiness_DB.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .HasColumnType("text");

                    b.HasKey("BrandId");

                    b.ToTable("Brand", "store");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Otro"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Bravo"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Dos coronas"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Gouda"
                        });
                });

            modelBuilder.Entity("MyBusiness_DB.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.HasKey("OrderId");

                    b.ToTable("Order", "store");
                });

            modelBuilder.Entity("MyBusiness_DB.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("numeric");

                    b.Property<int?>("UnitOfMeasurementId")
                        .HasColumnType("integer");

                    b.HasKey("ProductID");

                    b.HasIndex("BrandId");

                    b.HasIndex("UnitOfMeasurementId");

                    b.ToTable("Product", "store");
                });

            modelBuilder.Entity("MyBusiness_DB.Models.ProductByOrder", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductID", "OrderID");

                    b.HasIndex("OrderID");

                    b.ToTable("ProductByOrder", "store");
                });

            modelBuilder.Entity("MyBusiness_DB.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("UnitOfMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitOfMeasurementId"));

                    b.Property<string>("UnitOfMeasurementInitials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitOfMeasurementName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UnitOfMeasurementId");

                    b.ToTable("UnitOfMeasurement", "store");

                    b.HasData(
                        new
                        {
                            UnitOfMeasurementId = 1,
                            UnitOfMeasurementInitials = "U",
                            UnitOfMeasurementName = "Unidad"
                        },
                        new
                        {
                            UnitOfMeasurementId = 2,
                            UnitOfMeasurementInitials = "Kg",
                            UnitOfMeasurementName = "Kilogramo"
                        },
                        new
                        {
                            UnitOfMeasurementId = 3,
                            UnitOfMeasurementInitials = "g",
                            UnitOfMeasurementName = "gramos"
                        },
                        new
                        {
                            UnitOfMeasurementId = 4,
                            UnitOfMeasurementInitials = "Lbs",
                            UnitOfMeasurementName = "Libras"
                        });
                });

            modelBuilder.Entity("MyBusiness_DB.Models.Product", b =>
                {
                    b.HasOne("MyBusiness_DB.Models.Brand", null)
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("MyBusiness_DB.Models.UnitOfMeasurement", null)
                        .WithMany("Products")
                        .HasForeignKey("UnitOfMeasurementId");
                });

            modelBuilder.Entity("MyBusiness_DB.Models.ProductByOrder", b =>
                {
                    b.HasOne("MyBusiness_DB.Models.Order", "Order")
                        .WithMany("ProductByOrders")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBusiness_DB.Models.Product", "Product")
                        .WithMany("ProductByOrders")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyBusiness_DB.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MyBusiness_DB.Models.Order", b =>
                {
                    b.Navigation("ProductByOrders");
                });

            modelBuilder.Entity("MyBusiness_DB.Models.Product", b =>
                {
                    b.Navigation("ProductByOrders");
                });

            modelBuilder.Entity("MyBusiness_DB.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
